# Generated by Django 2.2.6 on 2019-11-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_friend_current_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
